### ISSUE TITLE
Remove LuceneSynonymsRewriter

### ISSUE THREAD

**Issue by renekrie** [querqy/querqy#100]
Remove LuceneSynonymsRewriter and its dependencies. 

The original intent of this rewriter was to support the Lucene synonyms syntax to configure query time synonyms. As we want to focus on synonyms via Common Rules and as the synonyms.txt file can easily be converted in a rules.txt file, we should remove this rewriter (and its dependency on 'Sequence' and lucene.FST). The corresponding Solr rewriter factory has been deprecated for a while.

**Comment by renekrie** [comment]
Implemented via PR #101

**Comment by ABasharEter** [comment]
Hi.
Regarding the rewriter removal can you please tell me what was the intuition for removing it?

The thing is, sometimes we need to have synonyms on index and query time for specific field. We were doing that using one file for each filed type to simplify synonyms management. By removing it we have to manage two different files one for index time that is synoynms.txt the other is rule.txt for query time; however, both will have the same data. Also, when we will change something in the schema we need to modify the rules.txt file as well as we have ond file for all query time synonyms. 

can you tell me if there was an issue with keeping it?

**Comment by renekrie** [comment]
Hi @ABasharEter,

We couldn't actually see a use case that would need this specific Rewriter: everything could be expressed using the syntax of the common rules rewriter and reducing dependencies on Lucene components would reduce our maintenance efforts. As far as I remember, the removal was triggered by a change in the lucene.FST implementation or interface, which meant that we'd have to create a new Querqy version specifically for the new Solr version (instead of maintaining just 1 version for Solr 8.1 and higher) - so we finally removed the rewriter that had been marked 'deprecated' for a while.

I guess that in your case I'd write a simple rule format converter, which shouldn't be too tricky.

Also, in the context of #76 it will be impossible in the future to share a resource (like rules.txt) between rewriters or between rewriters and other components as rewriters will be configured using a single REST call that should not reference any external resources - so sharing a resource like 'synonyms.txt' with TokenFilters will not be possible.
