### ISSUE TITLE
Solr Plugin: Current approach of applying reranking leads to performance degradation

### ISSUE THREAD

**Issue by mkr** [querqy/querqy#104]
We currently wrap the generated main query in a RankQuery
* when boosts are applied and parameter `qboost.method` = `rerank`
* when an external rerank query is provided using parameter `querqy.rq`

Wrapping the main query incurs performance penalties when Solr needs to evaluate the main query multiple times. Facetting with facet exclusions seems to be one of the cases.

We should not replace the main query but set main and rank query individually on the `org.apache.solr.handler.component.ResponseBuilder` (using `#setQuery` and `#setRankQuery`, respectively)

**Comment by renekrie** [comment]
That makes a lot of sense to me!
