### ISSUE TITLE
Assure JDK 12 compatibility

### ISSUE THREAD

**Issue by renekrie** [querqy/querqy#107]
Under JDK12 we get at least this runtime error:

```<pre>java.lang.IncompatibleClassChangeError: Method &apos;org.apache.lucene.index.Term querqy.lucene.LuceneQueryUtil.toLuceneTerm(java.lang.String, java.lang.CharSequence, boolean)&apos; must be Methodref constant ```

when using the ClassicWordBreakCompoundRewriter (which should be removed in Querqy 5 in favour of the WordBreakCompoundRewriter).

**Comment by renekrie** [comment]
We should still support JDK 8 in accordance with Solr Java version requirements ( https://lucene.apache.org/solr/guide/8_6/solr-system-requirements.html)

**Comment by mkr** [comment]
This looks more like a dependency issue, possibly with different versions of Lucene in the classpath. Happy to support debugging if this is still an issue.

**Comment by renekrie** [comment]
Thank you @mkr - this might indeed explain this concrete case. It happened when multiple integration tests were run in an undefined order and it looked that some of them left the setup in an unstable state.

However, as we are building Querqy using JDK 8 with Java 8 as the target version, I wonder how sure we can be that it runs fine under Java 12. What I have in mind is setting up GitHub actions for many different environments (Java/Solr versions) and run a few integration tests that way. As I'm not an expert enough in this field to set this up quickly, if someone else could take the lead and try to set this up it would be a great help and provide an even more robust testing for Querqy.

**Comment by renekrie** [comment]
Fixed via #141
