### ISSUE TITLE
Configurable list of exclusions for decompounding

### ISSUE THREAD

**Issue by mkr** [querqy/querqy#121]
Although the current decompounding algorithm validates candidates against a dictionary field it can still produce false positives if all candidates are part of a document but still unrelated. Example: `slipper -> slip, per`. This case could be prevented by configuring a `minBreakLength` greater than 3. It would still be good to be able to configure "false positives" that should never be split or be result of a combination of adjacent terms.

**Comment by renekrie** [comment]
See PR #122

**Comment by renekrie** [comment]
Implemented by #122
