### ISSUE TITLE
Facilitate query rewriting outside of search engines

### ISSUE THREAD

**Issue by JohannesDaniel** [querqy/querqy#123]
Handling the query rewriting inside of (Lucene based) search engines as it is done currently has pros and cons. 

Among the pros of rewriting inside are:
- there is a direct access to Lucene (helpful e. g. for wordbreak rewriting)
- the rewriting can be optimized towards an out-of-the-box usage
- more accurate regarding matching and scoring - especially for Solr, rewriting outside is painful, ugly and partially impossible, but Elasticsearch also has limitations here

Among the cons of rewriting inside are:

- querqy updates requires developers to change the deployment of the stateful search engine, which is in general slower and more risky than changing the deployment e. g. of a microservice
- using querqy requires developers (in many cases) to host and to maintain the search engine themselves - external hosting or using querqy in combination e. g. with Amazon CloudSearch is poorly supported
- Elasticsearch does not allow to change its response format - the decorations feature therefore is currently not really valuable for ES users (e. g. because you cannot pass query-dependent information to a search result page)
- The output of algorithms for spell correction, query relaxation or the like could be embedded into query rewriting, either to diminish the impact of false positives or to enhance their value. However, stuff like Tensorflow should not be deployed in Solr or ES, but rather in a service.

For sure there are a lot more pros and cons, but the mentioned ones should be already enough to think about a better flexibility in querqy also to allow users to do the rewriting (or parts of it) outside of the search engine (I have not listed the painful core reload for Solr here, as I think this should be solved soon). Finally, I think rewriting inside or outside is not mutually exclusive. Maybe we can even get the best of both.

Reasonable first steps:

- Enhancing the builder lib of the querqy-core model to allow querqy queries to be transformed to JSON, consumable by Solr and ES (given they include querqy).
- Enhancing querqy-solr and querqy-elasticsearch to make the JSON output of querqy-core easily consumable.
- Enhancing querqy-core to facilitate its usage (e. g. creating rewrite chains via builders, enhancing rewriters by builders, ...)
- Facilitating the rewriting of nested clauses by enhancing the querqy-core query model

**Comment by renekrie** [comment]
A problem to consider: the term query cache - which memorises the fields that generated terms (don't) expand to in Lucene query building - cannot be pre-filled when the rules are loaded outside the search engine while the Lucene query is built inside the search engine. cc @JohannesDaniel

**Comment by JohannesDaniel** [comment]
Is this a problem, if the respective parameters are not used? Otherwise, it is simply an entry in "limitations" in the docs.

**Comment by renekrie** [comment]
It's a limitation - you cannot pre-fill the cache

**Comment by renekrie** [comment]
It's a limitation - you cannot pre-fill the cache
