### ISSUE TITLE
Allow weighted synonyms

### ISSUE THREAD

**Issue by tboeghk** [querqy/querqy#128]
In our environment, we utilize so-called `subtopics` a lot. They are expansions of a term, but not real equal synonyms. Therefor we'd like to add those as lower boosted synonyms (e.g. `0.5`) to the query. An example would be:

```
cutlery =>
   SYNONYM(0.5): fork knife
```

If the user searches for `cutlery`, the recall will contain documents matching `cutlery`, `fork` and `knife` but documents matching `cutlery` will be ranked higher.

@tkaessmann and I are currently building a PR implementing this.

**Comment by pbartusch** [comment]
hi @tboeghk (fyi @renekrie) , that'll might impact the possibilities we offer the search-manager in SMUI.
but - quick thought on that: maybe your use case can be addressed by adding a synonym with a corresponding boost/penalise , like

`
SYNONYM: fork nife
UP(0.5): fork nife
`

have you discussed that?

**Comment by tkaessmann** [comment]
The feature will be completely optional. Therefore I don't think that it will affect SMUI. If you define the `SYNONYM` rule without any boosting, it will use the default value of `1.0`.

**Comment by renekrie** [comment]
We'd have to think about what the boost factor means. SYNONYM(0.5) - 0.5 compared to other synonyms? or to tokens without a synonym? Or is it the same as UP(0.5) - which heavily interferes with negative boosting (https://github.com/querqy/querqy/wiki#negative-scores-not-allowed-in-lucenesolr-80).

**Comment by tboeghk** [comment]
I drafted a PR with the proposed change. It's still rough and needs testing. 

The basic idea is to multiply the synonym weight as a factor to the field weight.
