### ISSUE TITLE
Allow to split rules file for Common Rules

### ISSUE THREAD

**Issue by renekrie** [querqy/querqy#14]
If Querqy runs in SolrCloud, the rules file for the Common Rules rewriter might hit the default Zookeeper max. file size of 1 MB. Allow to configure a (comma-separated) list of rules files.

**Comment by magro** [comment]
Or, if the number of rules files is not known at configuration time, it would be cool to be able to configure rules*. This could be implemented like "start counting i at 1 and look for files incrementing i until there's no file rules$i".

**Comment by renekrie** [comment]
This will be covered by #76. Closing this issue now.
