### ISSUE TITLE
[Housekeeping] CharSequence interface method toString() is not correctly implemented

### ISSUE THREAD

**Issue by JohannesDaniel** [querqy/querqy#145]
The interface CharSequence includes the method `toString()` with the following description:
```
    /**
     * Returns a string containing the characters in this sequence in the same
     * order as this sequence.  The length of the string will be the length of
     * this sequence.
     *
     * @return  a string consisting of exactly this sequence of characters
     */
```

Therefore, all classes implementing CharSequence directly or indirectly (e. g. via ComparableCharSequence) should implement the method according to this definition. This is not the case for:
* querqy.rewrite.commonrules.model.Term
* querqy.model.Term

**Comment by renekrie** [comment]
Implemented by #152
