### ISSUE TITLE
[Solr] DECORATE not returned

### ISSUE THREAD

**Issue by pbartusch** [querqy/querqy#153]
**Steps to reproduce:**

* Start Chorus.
* Maintain & deploy a "REDIRECT Rule" in SMUI (http://localhost:9000/), e.g.: "terms" redirects to "/terms-and-conditions.html".
* Retrieve the Solr response directly (bypassing Blacklight): http://localhost:8983/solr/ecommerce/select?q=terms&qt=querqy.

**Expected:**

The Solr response should contain a block `<arr name="querqy_decorations">` with the corresponding redirect instruction.

**Actual:**

No `querqy_decorations` block is returned.

**Further information:**

At the time of filing this bug, Chorus depends on the following Querqy version:

`
querqy-solr-4.9.lucene810.0-jar-with-dependencies.jar
`

**Comment by renekrie** [comment]
This has been fixed by #124. Similar to info logging, decorations could be lost in multi-shard setups. Please upgrade to the latest Querqy version.
