### ISSUE TITLE
Word break rewriter: move protected words config under 'decompound'

### ISSUE THREAD

**Issue by renekrie** [querqy/querqy#168]
Currently the words protected from decompounding are configured as a direct property of the `config` object in Querqy for Solr.  It should be a child of `decompound` as it is not applicable to compounding.

```
{
    "class": "querqy.solr.rewriter.wordbreak.WordBreakCompoundRewriterFactory",
    "config": {
         "dictionaryField" :  "dictionary",
         "lowerCaseInput": true,
         "decompound": {
             "maxExpansions": 5,
             "verifyCollation": true
         },
         "morphology": "GERMAN",
         "reverseCompoundTriggerWords": ["for"],
         "protectedWords": ["slipper"]

    }
}
```

**Comment by mkr** [comment]
I would think a "protected word" would also be a false positive for the compounder, wouldn't it?

**Comment by renekrie** [comment]
Indeed, thank you! - Closing this issue
