### ISSUE TITLE
Improve debug output and info logging on replace rewriter

### ISSUE THREAD

**Issue by ghost** [querqy/querqy#181]
**problem**:
There is no debug output nor info logging present for the replace rewriter.

We want to log information about:
- the plain query terms after the replacement took place
- the applied replace rules

**implementation**:
Encapsulate info logging and debug output in ContextAwareQueryRewriter.
Add info logging and debug output in replace rewriter.

**Comment by renekrie** [comment]
Makes sense to me but I'd rather split this into info logging vs. debug response output - except you have a 'joint' PR upcoming?! @TomGilke2468

**Comment by renekrie** [comment]
Resolved by #182
