### ISSUE TITLE
Generalise AbstractLoggingRewriter

### ISSUE THREAD

**Issue by renekrie** [querqy/querqy#184]
We currently have 

`AbstractLoggingRewriter extends AbstractNodeVisitor<Node>`

On the other hand, we never assume that the visit() methods return a Node object. To provide greater flexibility to subclasses of the AbstractLoggingRewriter we should change this to 

`AbstractLoggingRewriter<T> extends AbstractNodeVisitor<T>`

**Comment by JohannesPeter1984** [comment]
I think we should apply the rule "components before inheritance" here and avoid having another abstract class.

**Comment by renekrie** [comment]
This is overcome by #375
