### ISSUE TITLE
IllegalStateException when using querqy with a solr fieldtype with ManagedSynonymGraphFilterFactory

### ISSUE THREAD

**Issue by Paul-Blanchaert** [querqy/querqy#261]
When using querqy with Solr fields that have a fieldtype that uses a ManagedSynonymGraphFilterFactory (at query time), an IllegalStateException is thrown (stacktrace is partly shown below).
It is clear that both are mutually exclusive: basically you want to use querqy synonym handling functionailty instead of the synonyms via the ManagedSynonymGraphFilterFactory.
However, users tend to just try to install querqy and "forget" to review the solr schema.
Not sure if "detection" of this problematic config should be implemented in querqy or not... but at least, it should be mentioned in the installation guide of querqy that a review of the solr schema with a removal of the synonym and stopword functionality from the Solr configuration is "strongly recommended".

"error":{
  "msg":"org.apache.solr.rest.schema.analysis.ManagedSynonymGraphFilterFactory not initialized correctly! The SynonymFilterFactory delegate was not initialized.",
  "trace":"java.lang.IllegalStateException: org.apache.solr.rest.schema.analysis.ManagedSynonymGraphFilterFactory not initialized correctly! The SynonymFilterFactory delegate was not initialized.\n\tat org.apache.solr.rest.schema.analysis.ManagedSynonymGraphFilterFactory.create(ManagedSynonymGraphFilterFactory.java:439)\n\tat org.apache.solr.analysis.TokenizerChain.createComponents(TokenizerChain.java:119)\n\tat org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:136)\n\tat org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:163)\n\tat querqy.lucene.rewrite.TermSubQueryBuilder.termToFactory(TermSubQueryBuilder.java:69)\n\tat querqy.lucene.rewrite.LuceneQueryBuilder.addTerm(LuceneQueryBuilder.java:325)\n\tat querqy.lucene.rewrite.LuceneQueryBuilder.visit(LuceneQueryBuilder.java:284)\n\tat querqy.lucene.rewrite.LuceneQueryBuilder.visit(LuceneQueryBuilder.java:29)\n\tat querqy.model.Term.accept(Term.java:59)\n\tat querqy.model.AbstractNodeVisitor.visit(AbstractNodeVisitor.java:28)\n\tat querqy.lucene.rewrite.LuceneQueryBuilder.visit(LuceneQueryBuilder.java:215)\n\tat querqy.lucene.rewrite.LuceneQueryBuilder.visit(LuceneQueryBuilder.java:29)\n\tat querqy.model.DisjunctionMaxQuery.accept(DisjunctionMaxQuery.java:25)\n\tat querqy.model.AbstractNodeVisitor.visit(AbstractNodeVisitor.java:36)\n\tat querqy.lucene.rewrite.LuceneQueryBuilder.visit(LuceneQueryBuilder.java:144)\n\tat querqy.lucene.rewrite.LuceneQueryBuilder.visit(LuceneQueryBuilder.java:29)\n\tat querqy.model.BooleanQuery.accept(BooleanQuery.java:19)\n\tat querqy.lucene.rewrite.LuceneQueryBuilder.createQuery(LuceneQueryBuilder.java:112)\n\tat querqy.lucene.QueryParsingController.transformUserQuery(QueryParsingController.java:324)\n\tat querqy.lucene.QueryParsingController.process(QueryParsingController.java:199)\n\tat querqy.solr.QuerqyDismaxQParser.parse(QuerqyDismaxQParser.java:89)\n\tat querqy.solr.QuerqyDismaxQParser.getQuery(QuerqyDismaxQParser.java:104)\n\tat org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:162)\n\tat querqy.solr.QuerqyQueryComponent.prepare(QuerqyQueryComponent.java:44)\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:312)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:214)\n\tat

**Comment by epugh** [comment]
There are legit use cases for synonyms...   Where we are using synonyms to literally mean "x == y", for example "colour and color".

**Comment by epugh** [comment]
There is an argument that Solr features like Synonyms and Stopwrods that are managed by end users SHOULD go into SMUI, since it is the "Search Management UI" ;-).

**Comment by Paul-Blanchaert** [comment]
Quick update on findings...
Seems to be a Solr issue introduced in version 8.3 ([SOLR-13739](https://issues.apache.org/jira/browse/SOLR-13739) looks a good candidate).
Requirements to reproduce: at least 2 shards, solrconfig with <schemaFactory class="ManagedIndexSchemaFactory"/> and schema with <filter class="solr.ManagedSynonymGraphFilterFactory" managed="en"/> ...

**Comment by Paul-Blanchaert** [comment]
More findings: only when the filename for the schema is "schema.xml"; exceptions don't occur when using "managed-schema" as filename

**Comment by Paul-Blanchaert** [comment]
Solr ticket raised: [SOLR-15829](https://issues.apache.org/jira/projects/SOLR/issues/SOLR-15829) IllegalStateException when using Managed resources

**Comment by renekrie** [comment]
Closing as this seems to be a Solr issue
