### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by magro** [querqy/querqy#3]
query should be available via maven central.

**Comment by mosabua** [comment]
I would like to reiterate on this request. We are trying to adopt querqy and potentially also contribute but the fact that it is not available in Maven Central (and uses a top level groupId instead of reverse DNS ownership or at least github naming) makes this more difficult than necessary.

**Comment by mosabua** [comment]
Bintray should support syncing to Maven Central so provided you fix the setup and configure the sync this would be easy.

**Comment by renekrie** [comment]
Thank you for bringing this up again, @mosabua. 

As this is not my primary field of expertise: A groupId like 'org.querqy' instead of 'querqy' would make it easier to use? I understand that this would be easier to keep in a repo directory structure, but I'm not getting the reference to reverse DNS.

**Comment by mosabua** [comment]
If you own the querqy.org domain name that would work. Otherwise you can use your github namespace. More guidelines are at 

https://central.sonatype.org/pages/producers.html
https://central.sonatype.org/pages/choosing-your-coordinates.html

https://www.youtube.com/watch?v=P_3yo-oU1To&feature=youtu.be

**Comment by mosabua** [comment]
A best practice is to use java package name using a reverse domain name you own. Same applies for groupId. E.g. maven.apache.org as DNS the Maven project owns results in groupId org.apache.maven and anything underneath like org.apache.maven.plugins ...

**Comment by mosabua** [comment]
If you follow those guidelines you can either set up publishing directly to central or sync from bintray to central. I dont know bintray in detail though..

**Comment by renekrie** [comment]
Thank you, @mosabua. I'm definitely in favour of publishing to Maven central. However, it might take a bit for me to get clarity under which organisation this should run. In any case, Querqy should be in Maven central by mid of this year. Please direct message me, in case the current solution is too big an impediment to you.

**Comment by mosabua** [comment]
If you change the groupId to  io.github.renekrie.querqy you can start publishing after a little setup. I can also build and publish for you potentially. If you want I can help you get access for release deployments and also get access myself and demo it all for you for starters. I do that for a bunch of other open source projects already..

**Comment by mosabua** [comment]
You can ping me via email or skype or whatever if you want to chat.

**Comment by sachinlala** [comment]
Hi @renekrie just wanted to check if you were able to progress the re-factor of the org-structure to publish querqy in maven central.
cc: @MighTguY

**Comment by renekrie** [comment]
We will approach this issue as follows:

- change groupId to org.querqy (#73)
- move repo to github.com/querqy
- publish to Maven Central under org.querqy

**Comment by mosabua** [comment]
Excellent

**Comment by renekrie** [comment]
We should remove querqy-antlr (#30) before going Maven Central so that we don't have to deploy a deprecated artefact to Central. I'm working on it - going to push a solution shortly.

**Comment by renekrie** [comment]
querqy-antlr (#30) had been removed (see previous comment)

**Comment by renekrie** [comment]
Querqy is available on Maven Central now for Solr 8.1 and higher (Querqy v4.7): https://search.maven.org/search?q=g:"org.querqy"

What remains left is porting this down to Querqy for earlier Solr versions and releasing it to the Central Repo.

**Comment by mosabua** [comment]
Awesome. Thanks

**Comment by renekrie** [comment]
Ported back to Querqy for Solr 7.2. We will not release Querqy for versions older than that to Maven Central.
