### ISSUE TITLE
Inconsistent formatting of response from Querqy in Solr

### ISSUE THREAD

**Issue by epugh** [querqy/querqy#317]
We have both `querqy.infoLog` AND `querqy_decorations`...   Seems like we should follow one pattern or the other!   To reduce chance of error and cognitive load on all the new folks adopting Querqy ;-)

**Comment by renekrie** [comment]
Just to make sure: You mean `.` vs `_`?

**Comment by epugh** [comment]
I was thinking about it...   and either way would be fine.    Just not both ways... ;-).     Json doesn't love the `.` in the parameters, so maybe `_`, but on the other hand solr does the `f.facet.blah` pattern a lot.
