### ISSUE TITLE
Querqy for solr not considering fq query parameter for rewriting

### ISSUE THREAD

**Issue by bitsInnovate00** [querqy/querqy#318]
### Description
In our solr query, the query filtering is happening via fq parameter rather than q parameter .  Both are functionally same . But querqy is not considering fq parameter for query rewriting . This is causing querqy integration to fail in our use case
Example query parameter  which is not working
q=*:*&fq=producttype:notebook&qf=producttype
Example query parameter  which is working
q=notebook&qf=producttype

**Comment by renekrie** [comment]
You should be able to use the Querqy query parser in `fq` using Solr's local param syntax (https://solr.apache.org/guide/8_11/local-parameters-in-queries.html), à la `fq={!querqy qf=producttype possible more params here}notebook`.

I'm closing this issue but feel free to post further questions here.
