### ISSUE TITLE
[Enhancement] Support for lucene 9

### ISSUE THREAD

**Issue by ps48** [querqy/querqy#330]
**Background:**
Lucene 9 removed/altered a couple of APIs & functions used in querqy-lucene. Below are the ones that hit up in my initial investigation. 

**Related Lucene change logs:**
* [LUCENE-8921](http://issues.apache.org/jira/browse/LUCENE-8921): IndexSearcher.termStatistics() no longer takes a TermStates; it takes the docFreq and totalTermFreq. And don't call if docFreq <= 0. The previous implementation survives as deprecated and final. It's removed in 9.0.

* [LUCENE-9562](http://issues.apache.org/jira/browse/LUCENE-9562): All binary analysis packages (and corresponding Maven artifacts) with names containing '-analyzers-' have been renamed to '-analysis-'.

* [LUCENE-3041](http://issues.apache.org/jira/browse/LUCENE-3041): The deprecated Weight#extractTerms() method has been removed

**Comment by ps48** [comment]
Thanks @renekrie, feels like #304 should be the way to go forward.

**Comment by anirudha** [comment]
@renekrie what the next step here, if we need to move faster ?

**Comment by renekrie** [comment]
This has finally be released as version `5.4.lucene900.0`
