### ISSUE TITLE
Addition of Facet Support

### ISSUE THREAD

**Issue by MighTguY** [querqy/querqy#51]
There are cases, where on the basis of the search terms we can set rules on what facets should come, also we can include multiple features in it like: 
1. Facet Sort Type
2. Facet Size
3. Facet Name

**Comment by renekrie** [comment]
@MighTguY Thank you for bringing up this idea!

I'm not sure that I want to do this in Querqy as we would loose the focus on query rewriting.

I think there already is a way to control facets just using the Querqy configuration and creating a specific implementation of the  querqy.infologging.Sink interface.

You could try the following:

rules.txt
```
<input> =>
  SYNONYM: <syn>
 @{
   _log: {
     "message": "log me",
     "facets": [
        {
           "name": "facet_name1",
          "limit": 10,
          "sort": "index"
        },
        {
           "name": "facet_name2",
          "limit": 10,
          "sort": "index"
        }
    ] 
 }@
```

`querqy.infologging.Sink#log(Object message, String rewriterId, SearchEngineRequestAdapter searchEngineRequestAdapter)` will receive a Map as parameter `message`. The _log Json object can be found in that map under the key "APPLIED_RULES". So you would have to create your own Sink implementation, that uses this object to read the facet information and pass it to the facet component (maybe it can manipulate the request params). Ut probably should also write the log message to some output. You might want to have a look at `querqy.solr.ResponseSink` for inspiration - but you'd need to pass the facet info to the Solr request already in log() - it would be too late in endOfRequest()

**Comment by renekrie** [comment]
@MighTguY Many thanks again for this idea.

I'm closing this issue as I think that nobody will work on this anytime soon and as there is a way implementing it with a custom info Sink.

We can always re-open it or create a new issue if needed.
