### ISSUE TITLE
Support Solr Config API

### ISSUE THREAD

**Issue by andywebb1975** [querqy/querqy#66]
As discussed today in Relevance Slack: I've found that attempting to add the Querqy query parser using the Solr Config API (in Solr 8.2) fails with the exception `java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class org.apache.solr.common.util.NamedList`. The command below is accepted (but is ineffective) only if the `rewriter` property is renamed:

```
{
  "create-queryparser": {
    "class": "querqy.solr.DefaultQuerqyDismaxQParserPlugin",
    "name": "querqy",
    "parser": {
      "class": "querqy.parser.WhiteSpaceQuerqyParser",
      "factory": "querqy.solr.SimpleQuerqyQParserFactory"
    },
    "rewriteChain": {
      "rewriter": {
        "class": "querqy.solr.SimpleCommonRulesRewriterFactory",
        "ignoreCase": true,
        "querqyParser": "querqy.rewrite.commonrules.WhiteSpaceQuerqyParserFactory",
        "rules": "rules.txt"
      }
    }
  }
}
```

**Comment by renekrie** [comment]
I think we should re-consider the approach to configuring Querqy in general and move towards its own API (request handler) to manage the configuration. This would allow us to validate the configuration before it is saved and also avoid the need for core/collection reloads on update.

**Comment by MighTguY** [comment]
I agree, with @renekrie  as this will also standardize with how querqy will be configured.

**Comment by renekrie** [comment]
Created #76 for a new general approach to rewriter definition

**Comment by andywebb1975** [comment]
Thanks Rene - shall I close this issue?

**Comment by renekrie** [comment]
> Thanks Rene - shall I close this issue?

I think we should leave it  open and x-ref the two issues until #76 has a clear outcome.

**Comment by renekrie** [comment]
This will be covered by #76. Closing this issue now.
