### ISSUE TITLE
Implement a number-unit-rewriter

### ISSUE THREAD

**Issue by JohannesDaniel** [querqy/querqy#72]
I am currently thinking about how a number-unit-rewriter could be implemented in Querqy.

The goal: A query like "tv 50 inch" is rewritten to a query like this
```
eq(
    boolq(
        dmq(
            term(
                *:"tv"
            ),
            term(
                *:"television"
            ),  
        ),  
        dmq(
            term(
                screen_size:50^20
            ),
            range(
                screen_size:[45 TO 50)^10
            ),
            range(
                screen_size:(50 TO 55]^10
            ),
            range(
                screen_size:[40 TO 45)^5
            ),
            range(
                screen_size:(55 TO 60]^5
            )
        )
    )
)
```

The rewriter configuration could roughly look like this:
```
<lst name="rewriter">
    <str name="class">querqy.solr.contrib.NumberUnitRangeRewriterFactory</str>
    <lst name="numberUnitDefinition">
        <!-- units can be defined with a factor the number is multiplied with, 
        e. g. for something like mm, cm, m -->
        <lst name="units">
            <str name="inch">1.0</str> 
        </lst>
        <!-- multiple fields should be configurable -->
        <str name="fields">screen_size</str>
        <lst name="boundaries">
            <lst name="upperBound">
                <str name="weight">10</str>
                <str name="bound">10%</str>
            </lst>
            <lst name="upperBound">
                <str name="weight">5</str>
                <str name="bound">20%</str>
            </lst>
            <lst name="lowerBound">
                <str name="weight">10</str>
                <str name="bound">10%</str>
            </lst>
            <lst name="lowerBound">
                <str name="weight">5</str>
                <str name="bound">20%</str>
            </lst>
        </lst>
    </lst>
</lst>
```

Probably, an option to keep the original token or to do something with it like concat / split can be added.

The more complex part is how to implement this in Querqy. So far I identified three options:

1. Not touching the query model and the LuceneQueryBuilder by creating a combination of filter and boost clauses (should be the worst option)
    - Enforces some kind of MUST for the range part
    - Requires a lot of clauses to be created
    - Feels like a hack

2. Using RawQuery for the ranges
    - Requires RawQuery to be a DisjunctionMaxClause
    - Requires the LuceneQueryBuilder to visit RawQuery and to create a RawQueryFactory that creates a query simliar like the method "Query parseRawQuery(final RawQuery rawQuery)" in class DismaxSearchEngineRequestAdapter

3. Enhancing the model by something like a range query
    - Requires the most comprehensive changes as the entire visiting has to be enhanced
    - Should be the cleanest solution

Personally, I am in favor of solution 2 even though it appears not to be the cleanest one. The solution does not require too deep changes on the plugin. Furthermore, making RawQuery compatible to be nested in DMQ could also make the plugin more flexible for future rewriters.

What do you think about this?

**Comment by renekrie** [comment]
Thank you for this great rewriter idea - needs a bit to let it sink in!  ;-)

**Comment by tomsquest** [comment]
Hi,

Our 2cents about this feature. No idea of implemenation, just giving you feedback on what we have, will have/need.

We have a custom solution around number-unit.
It relies on adhoc code for converting a unit to another (meter to centimeters).
Nothing relying on Querqy currently.

We also have an idea for a feature where unit and attribute could be combined.
Example: when a user search for `board 90 centimeters` and we only have `100 centimeters board` that can be cut, then this board should be found.

**Comment by JohannesDaniel** [comment]
@renekrie 
As you mentioned that you are not sure about how these range queries affect the scorings, I did a couple of tests. Lucene appears to score a range query that is e. g. embedded in a Boolean Query by 1.0.

**Comment by JohannesDaniel** [comment]
I am currently working on this. I will create the PR for this soon.

@renekrie is there already some progress regarding querqy.org? This feature definitely requires some documentation & explanation in order to be configured properly for a certain use-case.

**Comment by renekrie** [comment]
> @renekrie is there already some progress regarding querqy.org? This feature definitely requires some documentation & explanation in order to be configured properly for a certain use-case.

Let's put it in the Wiki repo for now. The new documentation (querqy.org or, maybe, readthedocs.org) is likely also to use some kind of markdown which makes copying it over easy.

**Comment by JohannesDaniel** [comment]
@renekrie just created PR. as the logic is quite complex, it might make sense to have a quick chat before you review for a common understanding.
@tomsquest rene told me that you have a requirement for digit-unit rewriting / filtering without an upper boundary. I considered this as a feature in the rewriter. probably you can check the implementation / logic / documentation when this is released and provide general feedback.

**Comment by renekrie** [comment]
Implemented. PR #82
