### ISSUE TITLE
Support compressed rewrite rule files

### ISSUE THREAD

**Issue by mkr** [querqy/querqy#77]
When using Querqy's rule-based rewriter one can quickly scratch the 1 MB size limit that Solrcloud (or Zookeeper) currently imposes on config files. While there are workarounds (such as increasing ZK's `jute.maxbuffer`) and more involved solution approaches (such as  #14) supporting GZ compression for rule files might already be a simple first step that eases the pain for most users.

**Comment by renekrie** [comment]
Merged. Will be released in querqy-4.7
