### ISSUE TITLE
Bug: java.lang.ClassCastException for MatchAllQuery in ReplaceRewriter

### ISSUE THREAD

**Issue by JohannesDaniel** [querqy/querqy#83]
The ReplaceRewriter does not check if the given ExpandedQuery is an instance of Query. The subsequent cast therefore leads to a ClassCastException if ExpandedQuery is an instance of MatchAllQuery.

**Comment by JohannesDaniel** [comment]
Created PR

**Comment by renekrie** [comment]
Fixed by #84
