### ISSUE TITLE
Support suffixes for ReplaceRewriter

### ISSUE THREAD

**Issue by JohannesDaniel** [querqy/querqy#86]
The ReplaceRewriter should support suffixes for replacements. Suffixes can be indicated by a wildcard at the beginning of a term, e. g. 
`*phones => phone`

Use cases:
* Compensate limitations of stemmers due to language dependencies, e. g. `*kameras => kamera`
* Facilitate the definition of subsequently applied synonyms, e. g `*phones => phone`

The ReplaceRewriter will replace the matched suffix (sub)string by the sequence on the right side. In order to avoid abusal usage leading to ambiguous behavior, we could consider some limitations for the usage of the suffixes. 

As I currently see no use case for using those suffix definitions within sequences of terms (e. g. `apple *phones => apple $1phone` or the like), using wildcards only will be allowed for single term input definitions.

**Comment by renekrie** [comment]
Hi @JohannesDaniel,

Sounds good to me! If you are looking for a way to implement the lookup for the suffixes: `TrieMap` can handle prefix lookups (`phone*`). So maybe you could just use a second TrieMap for the suffix lookup but reverse the characters (`*phones`  - put into TrieMap as  `senohp*` and look up `smartphones` as `senohptrams`) - but probably you already knew this trick ;-)

**Comment by JohannesDaniel** [comment]
I already did some tests here, I will either implement something like a ReversedCharSequence or ReversedTrieMap or both.

**Comment by renekrie** [comment]
Implemented, PR #87
