### ISSUE TITLE
BUG: NumberUnitRewriter throws NumberFormatException for input "." or "," 

### ISSUE THREAD

**Issue by JohannesDaniel** [querqy/querqy#89]
For the case that a query contains a token which char seq equals "," or ".", e. g. "token1 , token2", the NumberUnitRewriter throws a NumberFormatException. 

The problem can be avoided by not using the NumberUnitRewriter or by using the ReplaceRewriter beforehand deleting tokens "," or ".".

**Comment by renekrie** [comment]
Fixed. PR #90
