### ISSUE TITLE
RewriterWatcher seemingly GC root causing memory leak

### ISSUE THREAD

**Issue by Selaron** [querqy/querqy#894]
On our Solr 9.4.1 instances we observe increasing memory footprint over time, mainly caused by an increasing number of instances of `java.net.FactoryURLClassLoader` each holding a 50 MByte instance of `querqy.rewrite.lookup.preprocessing.GermanNounNormalizer`.

When initially starting Solr, we observe 5 of these instances in heap, one for each solr collection having querky configuration.

Some days later we observed 60+ of these.

We figured out that the GC roots to these `GermanNountNormalizer` instances are instances of `querqy.solr.ZkRewriterContainer$RewriterWatcher` with `enabled=false`.

Investigating your source code we found  in `querqy.solr.ZkRewriterContainer#newRewriterWatcher` you instantiate new `RewriterWatcher`, disable the obsolete one but there does not seem to exist a mechanism actually removing the obsolete instance from `org.apache.zookeeper.ZKWatchManager#dataWatches`, so this collection grows over time.

I assume you should inform `ZKWatchManager` about the old `RewriterWatcher` to be obsolete and to get it removed, but I'm unsure whether Zookeeper should actually do recognize this automagically and fails to do so in our configuration.

The incoming GC root path to one of these instances of `GermanNounNormalizer` looks like this:

![image](https://github.com/user-attachments/assets/f4a41e88-dd65-458f-a217-af489a3fc188)

**Comment by renekrie** [comment]
Thank you @Selaron ! That's a great catch! I'll have a look and try to find a solution.

**Comment by renekrie** [comment]
One question to understand the problem better @Selaron: Do you explicitly delete rewriters through Querqy's API or do you only save and update rewriters?

**Comment by Selaron** [comment]
After further investigation I consider our regular collection reload action to trigger this behavior. On the affected collections we invoke the Solr Uri `collections?action=RELOAD&name=some_affected_collection` to make sure everything is up to date and in sync.

The scheduled reloads and memory consumption show strong correlation in our heap monitoring graphs.

**Comment by renekrie** [comment]
Yes, that makes a lot of sense. What we see is that the reference to that large data object in `GermanNounNormalizer` is via its class (it is referenced by a static variable). What probably happens: each Solr core has its own classloader that caches its own `GermanNounNormalizer` class object and the Watcher instances indirectly reference that classloader. Upon core reload the Watcher doesn't get cleaned up because it is referenced by ZK(WatchManager) - which lives outside the cores. 

When we wrote the code, it was impossible to delete a watcher in ZK (hence the disabling). We should now add an onClose hook to the core and disable the rewriter watchers there. (And also review the watcher creation / disabling in other places)

**Comment by renekrie** [comment]
@Selaron It might take a bit to implement and especially to test this - if that's an urgent production issue you might consider putting Querqy into a Solr-global classpath (maybe SOLR_HOME/lib? - https://solr.apache.org/guide/solr/latest/configuration-guide/libs.html). I haven't tried this out but the idea/hope would be that `GermanNounNormalizer` would then be loaded via the global classloader and not one class per core.

**Comment by mkr** [comment]
I remember situations where missing watch removal caused memory leaks and the trend was to use higher level abstractions such as the ones provided by [Curator](https://curator.apache.org/docs/recipes-node-cache/) instead. Maybe that would provide a cleaner implementation? I second the suggestion to use the global classloader as the current deployment has [other issues](https://github.com/querqy/querqy/issues/491).

**Comment by renekrie** [comment]
See PR #913. 

Solr 9.0 doesn't provide direct access to ZK - so I'm removing the integration test and the support for it. Using an older version of Querqy with Solr 9.0 has a risk of running into the memory leak above, especially with collection reloads. To work around it, try to put the Querqy jar into `solr-home/lib` (which should solve the issue that old core-specific classloaders keep in memory) or occasionally save your rewriters and add and remove a dummy rewriter, which should fire (and remove) stale watchers in ZK that might have survived collection reloads.

**Comment by Selaron** [comment]
After moving the .jar directly into `$SOLR_HOME/lib` we have only one instance of `GermanNounNormalizer` left and thus more free memory from start than before. Additionally this is not leaking memory on config reload. Thanks for the hint and your remarkable effort.

I'm still watching this issue and am looking forward to confirm this fixed on future release.

**Comment by renekrie** [comment]
@Selaron Thank you!
I have released a version that should fix the issue even if you put the .jar file into a core/collection-specific lib folder. Is there a chance that you could try it out in your "old" setup?
Many thanks!

**Comment by Selaron** [comment]
@renekrie After upgrading to `querqy-solr-5.8.lucene961.0-jar-with-dependencies.jar` the GC roots from ZKWatchManager are gone when reloading the collections multiple times.

But I found new GC roots on the heap dump from Log4JLogEvents caused by NullPointerExceptions which I also found in the logs:

```
q.s.ZkRewriterContainer Error processing WatchedEvent for rewriter common_rules => java.lang.NullPointerException: Cannot invoke "org.apache.solr.common.cloud.SolrZkClient.wrapWatcher(org.apache.zookeeper.Watcher)" because "this.zkClient" is null
	at querqy.solr.ZkRewriterContainer.newRewriterWatcher(ZkRewriterContainer.java:417)
java.lang.NullPointerException: Cannot invoke "org.apache.solr.common.cloud.SolrZkClient.wrapWatcher(org.apache.zookeeper.Watcher)" because "this.zkClient" is null
	at querqy.solr.ZkRewriterContainer.newRewriterWatcher(ZkRewriterContainer.java:417) ~[?:?]
	at querqy.solr.ZkRewriterContainer.onRewriterChanged(ZkRewriterContainer.java:367) ~[?:?]
	at querqy.solr.ZkRewriterContainer$RewriterWatcher.process(ZkRewriterContainer.java:432) ~[?:?]
	at org.apache.solr.common.cloud.SolrZkClient$ProcessWatchWithExecutor.lambda$process$1(SolrZkClient.java:1055) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:294) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]

```

I consider these GC roots likely to be cleaned up at some later point in time, never the less there seems to be some null check missing.

 
![grafik](https://github.com/user-attachments/assets/60a1966b-a4bb-45f3-86c6-cad1e1e256b0)
