### ISSUE TITLE
Enable handling of the non matching part for prefix and suffix matches

### ISSUE THREAD

**Issue by JohannesDaniel** [querqy/querqy#93]
A prefix/suffix rule like `spühl* => spül` should not only allow to handle the matching part, but also to handle the non-matching part. The non-matching part will be expressed with $1 (analogue to common rules). This will help to 
- remove non-matching parts `günstig* => günstig` or
- to split terms `abc* => abc $1`

Existing configurations will be needed to be slightly modified. An existing rule like `spühl* => spül` will be needed to be refactored to `spühl* => spül$1`. However, as this feature has not been publicly presented or documented so far, this should not be a big issue.

**Comment by renekrie** [comment]
Fixed #96
